### ISSUE TITLE
Inform the user better about incoming calls

### ISSUE THREAD

**Issue by erikinkinen** [cutie-shell/cutie-phone#2]
Ring tone would be needed.

And a way to answer/reject from lockscreen, which I'd like to implement using a custom extension to the notification spec. (The spec allows custom extensions within the extra data dict: X-*Vendor*-*Prop*)

**Comment by erikinkinen** [comment]
https://github.com/cutie-shell/cutie-phone/commit/b5cd9b3bd0e681807aae0866c37c0c8ac577f693 adds a ringtone.

**Comment by erikinkinen** [comment]
[cutie-ongoing-call](https://github.com/cutie-shell/cutie-ongoing-call) now contains the parts to notify users about incoming calls. It uses wlr-layer-shell to overlay itself on the screen and it will be overlaid on top of lock screen as well. It also turns on the screen for the incoming call through wlr-output-power.

I think these improvements fully resolve this issue. @arpio23 , please confirm.

**Comment by arpio23** [comment]
Yes, works fine for me.
